### ISSUE TITLE
Rename to <vaadin-split-layout>

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-split-panel#3]
While writing the documentation, I found myself mentioning the word “layout” frequently. Especially when describing the horizontal and vertical orientation modes.

IMO, it is confusing to read as: “horizontal panel” and “vertical panel”. For example, the following panel can be described as both vertical (has vertical layout) and horizontal (width > height) at the same time:

```html
<vaadin-split-panel vertical style="width: 320px; height: 200px;">
  <div>first</div>
  <div>second</div>
</div>
```

If we rename the element to `<vaadin-split-layout>`, then these words will make much more sense together, giving the exact meaning: it’s in a horizontal/vertical split layout:

```html
<vaadin-split-layout vertical>
  <div>top</div>
  <div>bottom</div>
</vaadin-split-layout>
```

This name fits well in the Polymer’s ecosystem, as there are elements named alike: `<app-header-layout>`, `<app-drawer-layout>`.

cc @jouni

**Comment by jouni** [comment]
Agreed that we change the name to vaadin-split-layout.
